version: "3.8"
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=todo_list'
      - 'POSTGRES_PASSWORD=12345'
      - 'POSTGRES_USER=postgres'
    ports:
      - '15432:5432'